export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS_SUCCESS = 'RECEIVE_ITEMS_SUCCESS';
export const RECEIVE_ITEMS_FAIL = 'RECEIVE_ITEMS_FAIL';

export const REQUEST_SUBMIT_CART = 'REQUEST_SUBMIT_CART';
export const RECEIVE_SUBMIT_CART_SUCCESS = 'RECEIVE_SUBMIT_CART_SUCCESS';
export const RECEIVE_SUBMIT_CART_FAIL = 'RECEIVE_SUBMIT_CART_FAIL';

export const UPDATE_CART_ITEM_QTY = 'UPDATE_CART_ITEM_QTY';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const TOGGLE_SORT_CART = 'TOGGLE_SORT_CART';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';